INSERT INTO marca (id, nome) VALUES (1,'FIAT')
INSERT INTO marca (id, nome) VALUES (2,'FORD')
INSERT INTO marca (id, nome) VALUES (3,'GM')
INSERT INTO marca (id, nome) VALUES (4,'WV')
INSERT INTO marca (id, nome) VALUES (5,'Gurgel')
INSERT INTO marca (id, nome) VALUES (6,'Targa')

INSERT INTO modelo (id, marca_id, nome) VALUES (1, 1, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 1, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 1, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 1, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 1, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 1, 'Modelo6')
INSERT INTO modelo (id, marca_id, nome) VALUES (1, 2, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 2, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 2, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 2, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 2, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 2, 'Modelo6')
INSERT INTO modelo (id, marca_id, nome) VALUES (1, 3, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 3, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 3, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 3, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 3, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 3, 'Modelo6')
INSERT INTO modelo (id, marca_id, nome) VALUES (1, 4, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 4, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 4, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 4, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 4, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 4, 'Modelo6')
INSERT INTO modelo (id, marca_id, nome) VALUES (1, 5, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 5, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 5, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 5, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 5, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 5, 'Modelo6')
INSERT INTO modelo (id, marca_id, nome) VALUES (1, 6, 'Modelo1')
INSERT INTO modelo (id, marca_id, nome) VALUES (2, 6, 'Modelo2')
INSERT INTO modelo (id, marca_id, nome) VALUES (3, 6, 'Modelo3')
INSERT INTO modelo (id, marca_id, nome) VALUES (4, 6, 'Modelo4')
INSERT INTO modelo (id, marca_id, nome) VALUES (5, 6, 'Modelo5')
INSERT INTO modelo (id, marca_id, nome) VALUES (6, 6, 'Modelo6')