CREATE TABLE MARCA  (ID INT, NOME VARCHAR(20), OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )
CREATE TABLE MODELO (ID INT, MARCA_ID INT, NOME VARCHAR(20), OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )
CREATE TABLE TICKET (ID INT, MODELO_ID INT, NUMERO INT, PLACA VARCHAR(20), OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )