CREATE TABLE MARCA  (ID INT NOT NULL, NOME VARCHAR(20) NOT NULL, OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )
CREATE TABLE MODELO (ID INT , MARCA_ID INT NOT NULL, NOME VARCHAR(20) NOT NULL, OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )
CREATE TABLE TICKET (ID INT NOT NULL, MODELO_ID INT NOT NULL, NUMERO INT NOT NULL, PLACA VARCHAR(20) NOT NULL, OPTLOCK INT DEFAULT 0, VERSION INT DEFAULT 0 )